### PR TITLE
add infra nodereal service

### PR DESCRIPTION
**Pull request by huihzhao**

### CODE REVIEW

**Comment by huihzhao** [comment]
Please help review and merge, thanks

**Comment by itsharshag** [comment]
Looks like the logo URL is still broken. Can you share the logo here with me on GitHub? Also, can you move NodeReal after Infura (as we are ranking items based on their popularity)?

**Comment by huihzhao** [comment]
> Looks like the logo URL is still broken. Can you share the logo here with me on GitHub? Also, can you move NodeReal after Infura (as we are ranking items based on their popularity)?
nodereal_logo

Yes, please find the log here.

**Comment by itsharshag** [comment]
Awesome. Thank you for the contribution and the help. Merging this pull request.

**Pull request merged**
